### ISSUE TITLE
Keep Mac Awake Option

### ISSUE THREAD

**Issue by simi1030** [SlidePilot/SlidePilot-macOS#27]
### Feature description
SlidePilot should keep awake the Mac. SlidePilot should prevent any screensaver or power down mode from being activated. 

In case of a mobile computer, SlidePilot should also watch the battery status. Below a certain battery level SlidePilot should allow the display to sleep or power mode mode. 

### Problems this feature would solve
Before the presentation starts or during a comprehensive discussion often the screensaver or power down mode is being activated. This distracts the presenter and the audience. The presenter has to interact, move the mouse and–in the worst case–has to reenter hers or his credentials. 

### Security Considerations
Especially in large presentation areas, many people are present and since this feature keeps the Mac awake everyone may access the Mac and may access confidential data since the Mac is not being locked. 

Maybe this feature should be disabled by default.

**Comment by columbbus** [comment]
That's a good idea! I guess if this is a feature you can activate in the preferences it is totally fine. Regarding the security, if you don't want someone to access your Mac you can always lock the Mac yourself, so I guess this should be no problem.
