### ISSUE TITLE
Show cursor in Presenter Display mode

### ISSUE THREAD

**Issue by Alalalalaki** [SlidePilot/SlidePilot-macOS#30]
### Problem Description

The cursor is only shown in Presentation mode. As a presenter I want to know if I am using a highlight cursor or not.

### Improvement Description

Also show the cursor in Presenter Display mode.

Thanks.

**Comment by columbbus** [comment]
That's a good idea, thanks!

**Comment by columbbus** [comment]
Something that's kind of related:
Being able to move the SlidePilot cursor also in the presentation window. This currently doesn't work as the cursor is only broadcasted from presenter to presentation window.

**Comment by Alalalalaki** [comment]
@columbbus Yes, this will be helpful.
