### ISSUE TITLE
More layout options

### ISSUE THREAD

**Issue by columbbus** [SlidePilot/SlidePilot-macOS#40]
### Problem Description
Currently there are 4 layout options:
* Current
* LHS: _Current_, RHS: _Preview_
* LHS: _Notes_, RHS: _Current_
* LHS: _Notes_, RHS: _Current_, _Preview_

### Improvement Description
1. Provide a way to combine the three options _Current_, _Preview_ and _Notes_ in every possible way.
2. Also provide a way to choose on which side (LHS, RHS) to display the options. This means, if the layout configuration LHS: _Notes_, RHS: _Current_ is possible, then LHS: _Current_, RHS: _Notes_ should also be possible.

### Additional context
Ideas on how to implement this improvement.
1. can be implemented by adding another menu item in Moderator, to show/hide _Current_. A few special cases:
    1. Only _Current_ is displayed: Disable the "Show/Hide Current Slide" menu item
    2. Only _Preview_ is displayed: When clicking on the menu item to hide _Preview_, automatically show _Current_ instead.
    3. Only _Notes_ is displayed: When clicking on the menu item to hide _Notes_, automatically show _Current_ instead.
2. can be implemented by adding a simple menu item (button), which switches LHS and RHS.

**Comment by maehne** [comment]
Would be really nice to have this flexibility in arranging the layout of the presentation console! How about selecting the contents of a pane in the presenter console via a context menu? If a view is selected, which is already visible in another pane, they get swapped out. Thus, it should be possible to set up the presentation console's layout with two selections. However, I wonder whether people would rather prefer to set the default layout in the preferences windows. Most of the times, user's probably want to show/hide the notes.

Probably worth a separate issue: In our classrooms, we have two projections. It would be nice if optionally also the previous slide could be shown in a separate full screen window. Then, maybe the presenter console should offer the option to show 4 panes (previous, current, and next slide as well as notes). Though, this would also impose new layout to efficiently use the screen estate.

**Comment by columbbus** [comment]
User poll:
Regarding the layout configuration (i. e. which slide is shown an how they are ordered), which of the following options do you prefer?
1. The layout is configured globally for the whole app and stays the same for every document you use. If you change the layout, it changes for all documents.
2. The layout configuration is saved per document. Every time you open a document, the layout you last configured with this document opened is displayed. When opening a new (never used) document, a default layout configuration is shown (which cannot be changed in the preferences).

**I would be happy if as many people as possible participate :)**
/polls "1. Global" "2. Per Document"

**Comment by maehne** [comment]
I think a global configuration makes more sense than a per document configuration. Personally, I would find it tedious to configure my preferred layout for each new document I would like to present with SlidePilot. However, it may be handy to allow a user to define several layout configuration among which he can easily switch via a menu. The last selected layout could maybe stored as part of the per document preferences. If it should get deleted in the meantime, SlidePilot should fall back to some default layout.

**Comment by columbbus** [comment]
Thanks for your contribution @maehne!

Personally, I also think that a global configuration is better. Adding presets for layout configurations however is a bit too much of possible configuration in my option. Since the layout can be quickly changed using shortcuts (or the upcoming layout editor), I think it should be either global or a per document configuration, but not both mixed.

**Comment by maehne** [comment]
Thanks for your reply @columbbus! Well, I primarily would use two layouts: One when I present slides without any notes and one for slides with notes. So, my basic needs are already currently covered. Things would change if the layout options would also cover the settings for different presentation situations, especially whether no, one, or two (or more) external screens are present. Since these might change between repeated presentations (rehearsal, presentation of the course slides in different classes taking place in different rooms with differing presentation infrastructure). Then, the capability to choose among different presentation profiles may become more handy. This is, e.g., an area where your competition OpenBoard also lacks behind, as it stubbornly assigns its windows according to the number assigned by the OS to the screen and interferes when users move these windows to different screens manually.
