### ISSUE TITLE
Better usage of empty space

### ISSUE THREAD

**Issue by columbbus** [SlidePilot/SlidePilot-macOS#41]
### Problem Description
There is a lot of wasted **vertical** space in SlidePilot presenter window. This is bad, when two slide are displayed above each other.

### Improvement Description
Provide a way to better use the vertical space. This can be achieved by:
* Resizing the timer/clock view
* Hiding the timer/clock view
* Reduce slide padding to a minimum (give an option in the settings, which can be toggled to use minimal padding or not)

Ideally, these settings are stored in the documents configuration.

**Comment by columbbus** [comment]
**Further Note:**
Resizing or hiding the timer/clock view will not help much if the slides are landscape, as the size of those slides are limited by the screens width, not height. So the height gain by reducing the timer/clock view won't benefit landscape oriented slide

**Comment by rasenjop** [comment]
I vote for that one. I have the notes visible all the time and then the slides preview (current and next) are vertically stacked and kind of small. I would consider placing the notes at the bottom (sort of landscape) as in Powerpoint (a larger "current slide" in the left half of the screen, and a smaller "next slide" with the notes beneath in the right half of the window).
