### ISSUE TITLE
SlidePilot as a PDF Viewer on Mac

### ISSUE THREAD

**Issue by jacquesdurden** [SlidePilot/SlidePilot-macOS#43]
I consider that the performance of SlidePilot to view PDF on Mac is far better than Preview and Skim, especially now that SlidePilot automatically refresh if the file has been updated. 
In fact, Preview and Skim blur the viewed PDF document during a fraction of second at each page change, which is painful, and it doesn't seem this will be solved soon. 

I'm thus wondering if it could be useful to allow SlidePilot to have a "PDF viewer mode", without the presentation context. 

There are just a few functionalities missing, such as 
- search a keyword in the PDF;
- Go/back option if we click on a link and we want to go back on the previous page;

Anyway, I'm already using SlidePilot to see my compiled latex-PDF live (for beamer slides) and I find it great!

**Comment by columbbus** [comment]
I'm afraid there are currently no plans to make a PDF viewer, based on SlidePilot. This would be accompanied by a lot of additional work. I hope you understand, that I would rather like to invest that time into the further development of the SlidePilot presentation app.

Also there are so many PDF viewers out there, that I think a stand-alone PDF viewer based on SlidePilot will have a hard time competing against the others, which probably won't do justice to the workload.

I would suggest you try other PDF viewers than Preview and Skim, for example Adobe Acrobat Reader. I haven't tried it out but I would assume that it performs best in comparison to all other PDF viewers.

I hope you understand the current decision and thank you for the compliments on SlidePilot!
