### ISSUE TITLE
Cursor not visible in canvas mode

### ISSUE THREAD

**Issue by pzawistowski** [SlidePilot/SlidePilot-macOS#46]
### Bug description
When I start drawing on a slide and then switch to canvas mode – the cursor disappears from the presentation window. The drawings appear without any problems.

### Steps to reproduce
- Start a presentation.
- Switch do drawing mode.
- Turn on cursor visibility.
- Switch to canvas mode.

### Expected behavior
The cursor movement should be visible on the presentation monitor along with the drawings.

### Actual behavior
Only the drawings can be seen.

### Details
* macOS Version: 10.15.7
* SlidePilot Version: 1.6.1.1

**Comment by columbbus** [comment]
Thank you for finding this! I've found the bug and fixed it. It will be available in the next smaller release.

**Comment by pzawistowski** [comment]
Thank you for the effort - I'll test it when the release arrives :-)
