### ISSUE TITLE
Keep drawings when quitting drawing mode and allow saving the annotated PDF after the presentation

### ISSUE THREAD

**Issue by maehne** [SlidePilot/SlidePilot-macOS#56]
### Problem Description

Currently drawings on slides get cleared when quitting the drawing mode. During lectures, it is very common to annotate manually slides. The students appreciate it if they get a copy of these annotated slides afterwards.

### Improvement Description

First step would be to keep the drawings on a slide once quitting the drawing mode. The second step would be to offer the possibility to save the resulting annotated PDF to a new file. It would be handy if the proposed file name would be preset to a sensible new name, e.g. `<original-name-of-pdf>_notes_<iso-date>.pdf` or `<original-name-of-pdf>_notes_<iso-date+time>.pdf`. As people might have different preferences, the template could be made configurable in the Preferences window.

### Alternative solutions

This functionality is offered by alternative applications, e.g., [OpenBoard](https://openboard.ch), which have their own shortcomings.

### Additional context

None.

**Comment by columbbus** [comment]
Thanks for your ideas on saving drawings. I am planning to implement this in the next release. Related #37

**Comment by maehne** [comment]
Thanks for your reply and promising software! I have tested many alternatives over the past years and once this feature is implemented, SlidePilot would be a good solution for my needs. 

You are certainly aware of your competition [OpenBoard](https://openboard.ch), [pdfpc](http://pdfpc.github.io/), [Présentation.app](http://iihm.imag.fr/blanch/software/osx-presentation/), and others on the desktop. However, on iPadOS, good solutions are still missing. [Explain Everything](https://explaineverything.com) and [PDF Expert](https://pdfexpert.com) are usable to present PDFs, but don't currently provide a presentation console feature and have no dedicated support for LaTeX Beamer notes.

**Comment by columbbus** [comment]
I am glad SlidePilot serves you as a good tool!

I also see a lot of potential and need in SlidePilot on iPadOS, however this is a bigger project which I currently don't have time for. But I hope to start with it sometime this year.
