### ISSUE TITLE
Change to a Big Sur style icon

### ISSUE THREAD

**Issue by matrix-ranger** [SlidePilot/SlidePilot-macOS#58]
I like this app very much and nearly do all my presentations with it. Just a small suggestion. Can we change the icon to one that matches Big Sur style? Maybe that is more natural if you are working on an iPadOS app already.

**Comment by columbbus** [comment]
Thanks for your feedback, I am glad you enjoy using SlidePilot. That sure is a good idea. The most straightforward approach would be to just transform the current circular background into a rounded rect.

Or did you maybe have something else in mind? Ideas are more than welcome.

**Comment by matrix-ranger** [comment]
Just changing the circular background would be great! The icon already looks brilliant. The only issue is that it does not look compatible with other rounded rect apps on Big Sur.
