### ISSUE TITLE
Embedded video does not play

### ISSUE THREAD

**Issue by hurwitzPID** [SlidePilot/SlidePilot-macOS#61]
### Bug description
Sometimes (but not always) an embedded video does not play in the presentation window although it plays in the presenter window.

### Steps to reproduce
1. Embed video (mp4) into pdf file with \movie command from the multimedia package.
2. Open slide pilot in dual screen mode.
3. Start video playback in presenter window by clicking on the play button.

### Expected behavior
The video plays in both the presenter and the presentation window.

### Actual behavior
Sometimes (maybe 1 of 10) the video does not play in presentation window, but it does play in the presenter window.

### Details
* macOS Version: 11.4
* SlidePilot Version: 1.6.2

**Comment by columbbus** [comment]
Would you mind supplying a demo PDF where you've experienced this issue?

**Comment by columbbus** [comment]
I'm afraid I could not reproduce the issue. If you are able to reproduce it with the current version and you can supply a demo PDF, feel free to reopen this issue.
