### ISSUE TITLE
Improve Drawing Mode

### ISSUE THREAD

**Issue by Alalalalaki** [SlidePilot/SlidePilot-macOS#63]
I hope that the smoothness of the draw could be improved and one can choose for the size or type of the draw.

**Comment by columbbus** [comment]
Could you elaborate on what you mean with smoothness?

And what do you mean with type? Solid/dashed lines or pen/pencil?

**Comment by Alalalalaki** [comment]
@columbbus It's very hard to describe "smoothness". I can only say that I feel drawing is more easily in apps like GoodNotes.

By type I mainly mean size but maybe also some roundness to make it more human-writing-like.
