### ISSUE TITLE
Slidepillot on M1 Macbooks and IPads?

### ISSUE THREAD

**Issue by jojo2203** [SlidePilot/SlidePilot-macOS#81]
Hello,

I have 2 questions:
1. does the program already run under the Macbooks with m1 processor?

2. is there a schedule for the ipad version, not the remote but the native app.

thank you.

**Comment by brabanod** [comment]
Hi,

1. Yes, SlidePilot is tested to run with M1 MacBooks
2. Unfortunately not at the moment. Since this is a side project, the development effort is unfortunately too high at the moment to handle it alone.

**Comment by jojo2203** [comment]
thank you for your answer, helps me
 

Gesendet: Dienstag, 13. September 2022 um 14:20 Uhr
Von: "columbbus" ***@***.***>
An: "SlidePilot/SlidePilot-macOS" ***@***.***>
Cc: "jojo2203" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [SlidePilot/SlidePilot-macOS] Slidepillot on M1 Macbooks and IPads? (Issue #81)


 

Hi,


	Yes, SlidePilot is tested to run with M1 MacBooks
	Unfortunately not at the moment. Since this is a side project, the development effort is unfortunately too high at the moment to handle it alone.
