### ISSUE TITLE
Hyperlink not work under split note mode

### ISSUE THREAD

**Issue by jianhuig** [SlidePilot/SlidePilot-macOS#82]
### Bug description
I found that the links in the pdf can not be clicked if I select the split note mode. If I choose text note mode, then everything works fine.
### Details
* macOS Version: Monterey 12.6
* SlidePilot Version: 1.8.0.1

**Comment by brabanod** [comment]
Could you describe it in a little more detail? Where are the notes you split (top, bottom, left, right). In which views do they not work? In all (preview, next slide, notes) or just in some?

**Comment by jianhuig** [comment]
I tried all of them (top, bottom, left, and right). It seems to work if I choose right. But If I choose anything else, it does not work for all views. Sometimes if I exit the full screen, the link works, but once I enter the full screen, it stops working again.

**Comment by brabanod** [comment]
Ok would you mind supplying a PDF with which you are experience these issue, so that reproducing the issue and debugging is easier?

**Comment by jianhuig** [comment]
[An_example_of_the_beamer_package__1_.pdf](https://github.com/SlidePilot/SlidePilot-macOS/files/10005221/An_example_of_the_beamer_package__1_.pdf)

This is an example from overleaf. In page 2, table of contents links would not work in the situations I described above.

**Comment by brabanod** [comment]
Thank you, I could reproduce the bug. And I remember working on this issue before, I thought I fixed it. Seems like I got some more investigation to do.
